spring:
  application:
    name: test_backend
  config:
    import[0]: nacos:dev?group=DEFAULT_GROUP
  cloud:
    nacos:
      config:
        server-addr: 1.12.59.169:8848
        username: nacos
        password: nacos
        namespace: test
        # 查到的配置返回的格式
        file-extension: yml