server:
  port: 7788
spring:
  mvc:
    servlet:
      # 配置这个，以确保DispatcherServlet在启动时被加载
      load-on-startup: 10

  security:
    user:
      name: user
      password: 12345
      roles: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Ymxl0103

mybatis-plus:
  mapper-locations: "classpath*:/mapper/**.xml"
